config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :tweets do
      collection do
        get :map
        end
      resources :likes, only: [:create, :destroy]
      end
      
    resources :users, only: [:show]
    resources :preparations
    root'tweets#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/preparation.rb
class Preparation < ApplicationRecord
    belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        tweets_path 
    end
    def after_sign_up_path_for(resource)
        tweets_path 
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
 def index
 end

 def link
 end
 
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
    end
    
      def destroy
         like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
         like.destroy
         redirect_back(fallback_location: root_path)
      end
end

app/controllers/preparations_controller.rb
class PreparationsController < ApplicationController
    def new
        @preparation = Preparation.new
    end
    def create
      preparation = Preparation.new(tweet_params)
      preparation.user_id = current_user.id
      preparation.save
      redirect_to user_path(current_user.id)
    end
    private
    def tweet_params
        params.require(:preparation).permit(:body)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  def top
    @tweets = Tweet.all
    @rank_tweets = Tweet.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}.first(3)
    render layout: false 
  end
  def index
    @tweets = Tweet.all
    if params[:search] == nil
      @tweets= Tweet.all
    elsif params[:search] == ''
      @tweets= Tweet.all
    else
      #部分検索
      @tweets = Tweet.where("body LIKE ? ",'%' + params[:search] + '%')
    end
  end   
  def new
    @tweet = Tweet.new
  end
  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    if tweet.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end
  def show
    @tweet = Tweet.find(params[:id])
  end
  def edit
    @tweet = Tweet.find(params[:id])
  end
  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end
  private
  def tweet_params
    params.require(:tweet).permit(:body, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
        @preparations = Preparation.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/preparations_helper.rb
module PreparationsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<%= link_to "ログイン", tweets_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/hello/link.html.erb
My name is GeekSalon.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Okayu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/57925cc063.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>

  <body>
  <header>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %>
   <% unless user_signed_in? %>
      <%= link_to "ログイン", new_user_session_path,class:'top' %>
      <%= link_to "新規登録", new_user_registration_path %>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% end %>
    <%= link_to "マップ", map_tweets_path %>
   <%= yield %>
  </header> 
  </body>
</html>

app/views/preparations/new.html.erb
<%= form_for @preparation do |f| %>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_field :body, :size => 140 %>
    </div>
    <%= f.submit "Tweetする" %>
<% end %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/tweets/index.html.erb
<h1>行先を決めよう！～Direction of trip～</h1>
<h3>みんなの行程</h3>
<h3>投稿を検索</h3>
   <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
<% if user_signed_in? %>
<%= link_to "新規投稿へ", new_tweet_path %>
<%= link_to "マイプラン作成", new_preparation_path %>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<% unless user_signed_in? %>
<%= link_to "ログイン", new_user_session_path %>
<%= link_to "新規登録", new_user_registration_path %> 
<% end %>
<% if user_signed_in? %>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% end %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.body %>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% end %>
      <% else %>
        <i class="far fa-heart"></i><%= t.likes.count %>
      <% end %>
      <%= link_to "詳細へ", tweet_path(t.id) %>
    </div>
  <% end %>
</div>

app/views/tweets/map.html.erb
<div class="flower">
<div class="japan_map">
<%= image_tag 'map2.png',class:'map'%>

    <span class="area_btn area1" data-area="1">北海道・東北</span>
    <span class="area_btn area2" data-area="2">関東</span>
    <span class="area_btn area3" data-area="3">中部</span>
    <span class="area_btn area4" data-area="4">近畿</span>
    <span class="area_btn area5" data-area="5">中国・四国</span>
    <span class="area_btn area6" data-area="6">九州・沖縄</span>
    <div class="area_overlay">
        <div class="pref_area">
            <div class="pref_list" data-list="1">
                <div data-id="hokkaido">北海道</div>
                <div data-id="aomori">青森県</div>
                <div data-id="iwate">岩手県</div>
                <div data-id="miyagi">宮城県</div>
                <div data-id="akita">秋田県</div>
                <div data-id="yamagata">山形県</div>
                <div data-id="fukushima">福島県</div>
                <div></div>
            </div>
            <div class="pref_list" data-list="2">
                <div data-id="ibaragi">茨城県</div>
                <div data-id="tochigi">栃木県</div>
                <div data-id="gunma">群馬県</div>
                <div data-id="saitama">埼玉県</div>
                <div data-id="chiba">千葉県</div>
                <div data-id="tokyo">東京都</div>
                <div data-id="kanagawa">神奈川県</div>
                <div></div>
            </div>
            <div class="pref_list" data-list="3">
                <div data-id="niigata">新潟県</div>
                <div data-id="toyama">富山県</div>
                <div data-id="ishikawa">石川県</div>
                <div data-id="fukui">福井県</div>
                <div data-id="yamanashi">山梨県</div>
                <div data-id="nagano">長野県</div>
                <div data-id="gihu">岐阜県</div>
                <div data-id="shizuoka">静岡県</div>
                <div data-id="aichi">愛知県</div>
                <div></div>
            </div>
            <div class="pref_list" data-list="4">
                <div data-id="mie">三重県</div>
                <div data-id="shiga">滋賀県</div>
                <div data-id="kyoto">京都府</div>
                <div data-id="osaka">大阪府</div>
                <div data-id="hyogo">兵庫県</div>
                <div data-id="nara">奈良県</div>
                <div data-id="wakayama">和歌山県</div>
                <div></div>
            </div>
            <div class="pref_list" data-list="5">
                <div data-id="tottori">鳥取県</div>
                <div data-id="shimane">島根県</div>
                <div data-id="okayama">岡山県</div>
                <div data-id="hiroshima">広島県</div>
                <div data-id="yamaguchi">山口県</div>
                <div data-id="tokushima">徳島県</div>
                <div data-id="kagawa">香川県</div>
                <div data-id="ehime">愛媛県</div>
                <div data-id="kouchi">高知県</div>
                <div></div>
            </div>
            <div class="pref_list" data-list="6">
                <div data-id="fukuoka">福岡県</div>
                <div data-id="saga">佐賀県</div>
                <div data-id="nagasaki">長崎県</div>
                <div data-id="kumamoto">熊本県</div>
                <div data-id="oita">大分県</div>
                <div data-id="miyazaki">宮崎県</div>
                <div data-id="kagoshima">鹿児島県</div>
                <div data-id="okinawa">沖縄県</div>
            </div>
        </div>
    </div>
</div>
</div>
<script>
$(function(){
    //地域を選択
    $('.area_btn').click(function(){
        $('.area_overlay').show();
        $('.pref_area').show();
        var area = $(this).data('area');
        $('[data-list]').hide();
        $('[data-list="' + area + '"]').show();
    });
    //レイヤーをタップ
    $('.area_overlay').click(function(){
        prefReset();
    });
    //都道府県をクリック
    $('.pref_list [data-id]').click(function(){
        if($(this).data('id')){
            var id = $(this).data('id');
            //このidを使用して行いたい操作をしてください
            //都道府県IDに応じて別ページに飛ばしたい場合はこんな風に書く↓
            window.location.href = 'https://travel.rakuten.co.jp/mytrip/ranking/spot-' + id;
            prefReset();
        }
    });
    //表示リセット
    function prefReset(){
        $('[data-list]').hide();
        $('.pref_area').hide();
        $('.area_overlay').hide();
    }
});
</script>

app/views/tweets/new.html.erb
<h1>GeekTwitter</h1>
<h3>新規Tweet</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
  </div>
  <div class="field">
   <%= f.label :image %>
   <%= f.file_field :image %>
  </div>
 <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>
<%= link_to "新規投稿ページへ", new_tweet_path %>

app/views/tweets/show.html.erb
<h1>おかゆ～Travel</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
 <p><%= @tweet.body %></p>
 <p><%= @tweet.created_at %></p>
  <% if user_signed_in? %>
    <% if current_user.already_liked?(@tweet) %>
      <%= link_to tweet_like_path(@tweet), method: :delete do %>
        <i class="fas fa-heart"></i><%= @tweet.likes.count %>
      <% end %>
    <% else %>
      <%= link_to tweet_likes_path(@tweet), method: :post do %>
        <i class="far fa-heart"></i><%= @tweet.likes.count %>
      <% end %>
    <% end %>
  <% else %>
   <i class="far fa-heart"></i><%= @tweet.likes.count %>
  <% end %>
</div>

<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
<li><%= user.email %></li>
<% end %> 
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>
<%= link_to "編集する", edit_tweet_path(@tweet.id) %>
<%= button_to "削除する", edit_tweet_path(@tweet.id), method: :delete %> 

app/views/tweets/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Okayu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>
    <body>
    <header>
  <% unless user_signed_in? %>
  <%= link_to "ログイン", new_user_session_path %>
  <%= link_to "新規登録", new_user_registration_path %>
  <% end %>
  <% if user_signed_in? %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  <% end %>
  <%= link_to "マップ", map_tweets_path %>
</header>
<div class="image-man">  

<%= image_tag 'sea.png', class:'sea' %>
<%= image_tag 'sun.png', class:'sun' %>
<h2>さぁ旅に出よう</h2>
</div>

<h2>このサイトで出来ること</h2>
<h2>思い出をシェアしよう</h2>
<h2>また旅に出よう</h2>
<div class="tweets-container">
    <% @rank_tweets.each do |t| %>
     <div class="tweet">
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.body %>
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
    <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>
      <%= t.created_at %>
      <%= link_to "詳細へ", tweet_path(t.id) %>
    </div>
  <% end %>
</div>
</body>
<script>
window.onscroll = function(){  
var scrollTop = window.pageYOffset ;  //スクロール量を代入する

if (scrollTop == 0 ) {   //最上部に戻ってきた時
$(".sea").css('opacity', '1')
  $('.sea').css('transition', '1s')

  $(".sun").css('opacity', '0')
  $('.sun').css('transition', '1s')
}
if (scrollTop > 5 ) {   //１０pxスクロールした時
  $(".sea").css('opacity', '0')
  $('.sea').css('transition', '1s')

  $(".sun").css('opacity', '1')
  $('.sun').css('transition', '1s')
}
}
</script>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>ここがあなたの旅のスタート♪</h1>
<p>メールアドレス : <%= @user.email %></p>
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
  
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>
<h2>マイプラン一覧</h2>
<% @preparations.each do |t| %>
  <%= t.body %>
<% end %>